import { Metadata } from 'next'
import styles from './page.module.css'

export const metadata: Metadata = {
  title: 'About | Rosa Iliou Archive',
  description: 'Generated by create next app',
}

export default function About() {
  return (
    <section>
      <h2>About</h2>
      <article className={styles.about}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Error quo quam
        ad quibusdam molestias, perferendis ducimus voluptate hic laudantium
        neque deserunt laboriosam expedita cupiditate. Accusantium perspiciatis
        laborum porro mollitia! Quia.
      </article>
    </section>
  )
}
