import NavBar from '@/components/NavBar'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Link from 'next/link'
import './globals.css'
import styles from './page.module.css'

const PRFont = localFont({
  src: './font/PFRegalTextPro-RegularA.woff2',
})

export const metadata: Metadata = {
  title: 'Rosa Iliou Archive',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={PRFont.className}>
        <div className={styles.container}>
          <header className={styles.header}>
            <Link href="http://localhost:3000/" className={styles.title}>
              <h1>Rosa Iliou Archive</h1>
            </Link>
          </header>
          <main className={styles.main}>{children}</main>
          <nav className={styles.nav}>
            <NavBar />
          </nav>
        </div>
      </body>
    </html>
  )
}
